development:
  cloud_name: "dmq3cpw6u"
  api_key: "298317697953782"
  api_secret: "buvE08NGeE9weBjCsQQUwUVph20"
production:
  cloud_name: "dmq3cpw6u"
  api_key: "298317697953782"
  api_secret: "buvE08NGeE9weBjCsQQUwUVph20"
